---
title: "Lecture four- hypothesis"
author: "Sarah"
date: "8/11/2021"
output: html_document
---

```{r}
data<-c(17, 16, 20, 18, 16, 19, 22, 13, 15, 17, 21, 14, 18, 12)
```

```{r}
result<-t.test(data, mu=20, alternative = "less", conf.level = 0.99)
```

```{r}
result
```

```{r}
sd(data)
```

```{r}
sqrt(14)
```

```{r}
data2<-read.csv("class.csv", header=T)
```

```{r}
str(data2)
```

```{r}
result2<-t.test(data2$MorningClass, data2$EveningClass, alternative = "greater")
```

```{r}
result2
```

```{r}
data("mtcars")
```


```{r}
chi_t<-chisq.test(mtcars$carb, mtcars$cyl)
```

```{r}
chi_t
```


CLASSWORK
```{r}
younger<-c(34, 22, 15, 27, 37, 41, 24, 19, 26, 36)
```

```{r}
older<-c(45, 38, 52, 48, 25, 39, 51, 46, 55, 46)
```

```{r}
dtlife<-data.frame(older, younger)
```

```{r}
life<-t.test(dtlife$younger, dtlife$older, alternative="two.sided")
```

```{r}
?t.test
```

```{r}
life
```

```{r}
stimulation<-c(12, 7, 3, 11, 8, 5, 14, 7, 9, 10)
```

```{r}
nostimulation<-c(8, 7, 4, 14, 6, 7, 12, 5, 5, 8)
```

```{r}
intaketest<-data.frame(stimulation, nostimulation)
```

```{r}
result3<-t.test(intaketest$stimulation, intaketest$nostimulation, alternative="less", paired = T)
```

```{r}
result3
```